on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2 # needed to deploy only new files in ftp-deploy v3.1.2

    # ftp-deploy - v4.3.3

    # - name: 📂 Sync files
    #   # You may pin to the exact commit or the version.
    #   # uses: SamKirkland/FTP-Deploy-Action@6647c2f8ad10f869fded8e5a6253c9da11d7fb47
    #   uses: SamKirkland/FTP-Deploy-Action@4.3.3
    #   with:
    #     # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
    #     server: sftp.csc.uvic.ca
    #     # FTP account username
    #     username: ${{ secrets.ftp_server_username }} 
    #     # FTP account password
    #     password: ${{ secrets.ftp_server_password }}
    #     # The server folder to deploy to.
    #     # optional, default is ./
    #     server-dir: ./public_html/site-staging/
    #     # Print changes instead of performing changes
    #     dry-run: true
    #     # files to exclude from the server
    #     exclude: |
    #       **/.git*
    #       **/.git*/**
    #       **/.github*
    #       **/.github*/**
    #       **/README.md

    # ftp-deploy - v3.1.2

    # - name: 📂 Sync files
    #   # You may pin to the exact commit or the version.
    #   # uses: SamKirkland/FTP-Deploy-Action@6647c2f8ad10f869fded8e5a6253c9da11d7fb47
    #   uses: SamKirkland/FTP-Deploy-Action@3.1.2
    #   with:
    #     # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
    #     ftp-server: sftp://sftp.csc.uvic.ca:22/public_html/site-staging
    #     # FTP account username
    #     ftp-username: ${{ secrets.ftp_server_username }} 
    #     # FTP account password
    #     ftp-password: ${{ secrets.ftp_server_password }}
    #     # other arguments
    #     git-ftp-args: --insecure --dry-run
       
    # web-deploy - v1.0

    # - name: 📂 Sync Files
    #   uses: SamKirkland/web-deploy@v1
    #   with:
    #     target-server: sftp.csc.uvic.ca
    #     remote-user: ${{ secrets.FTP_SERVER_USERNAME }}
    #     # private-ssh-key: ${{ secrets.ftp_server_password }}
    #     private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     ssh-port: 22
    #     destination-path: ~/public_html/site-staging/
    #     rsync-options: --dry-run --archive --verbose --compress --delete-after --human-readable --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore

    # sftp-deploy-action - v1.2.4

    - name: Deploy file
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
          username: ${{ secrets.FTP_SERVER_USERNAME }}
          server: sftp.csc.uvic.ca
          port: 22
          local_path: './*'
          remote_path: '/public_html/site-staging'
          sftp_only: true
          password: ${{ secrets.FTP_SERVER_PASSWORD }}