# DEPLOY WEBSITE TO STAGING ON PUSH TO RELEASE BRANCHES
on:
  push:
    branches:
      - 'release-v*'
name: 🚀 Deploy website to staging on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2 # needed to check commit differences to deploy only new files

    # ftp-deploy - v4.3.3

    # - name: 📂 Sync files
    #   # You may pin to the exact commit or the version.
    #   # uses: SamKirkland/FTP-Deploy-Action@6647c2f8ad10f869fded8e5a6253c9da11d7fb47
    #   uses: SamKirkland/FTP-Deploy-Action@4.3.3
    #   with:
    #     # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
    #     server: sftp.csc.uvic.ca
    #     # FTP account username
    #     username: ${{ secrets.ftp_server_username }} 
    #     # FTP account password
    #     password: ${{ secrets.ftp_server_password }}
    #     # The server folder to deploy to.
    #     # optional, default is ./
    #     server-dir: ./public_html/site-staging/
    #     # Print changes instead of performing changes
    #     dry-run: true
    #     # files to exclude from the server
    #     exclude: |
    #       **/.git*
    #       **/.git*/**
    #       **/.github*
    #       **/.github*/**
    #       **/README.md

    # ftp-deploy - v3.1.2

    # - name: 📂 Sync files
    #   # You may pin to the exact commit or the version.
    #   # uses: SamKirkland/FTP-Deploy-Action@6647c2f8ad10f869fded8e5a6253c9da11d7fb47
    #   uses: SamKirkland/FTP-Deploy-Action@3.1.2
    #   with:
    #     # Deployment destination server & path. Formatted as protocol://domain.com:port/full/destination/path/
    #     ftp-server: sftp://sftp.csc.uvic.ca:22/public_html/site-staging
    #     # FTP account username
    #     ftp-username: ${{ secrets.ftp_server_username }} 
    #     # FTP account password
    #     ftp-password: ${{ secrets.ftp_server_password }}
    #     # other arguments
    #     git-ftp-args: --insecure --dry-run
       
    # web-deploy - v1.0

    # - name: 📂 Sync Files
    #   uses: SamKirkland/web-deploy@v1
    #   with:
    #     target-server: sftp.csc.uvic.ca
    #     remote-user: ${{ secrets.FTP_SERVER_USERNAME }}
    #     # private-ssh-key: ${{ secrets.ftp_server_password }}
    #     private-ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    #     ssh-port: 22
    #     destination-path: ~/public_html/site-staging/
    #     rsync-options: --dry-run --archive --verbose --compress --delete-after --human-readable --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore

    # sftp-deploy-action - v1.2.4

    # - name: 📂 Deploy files to Server
    #   uses: wlixcc/SFTP-Deploy-Action@v1.2.4
    #   with:
    #       username: ${{ secrets.FTP_SERVER_USERNAME }}
    #       server: sftp.csc.uvic.ca
    #       port: 22
    #       local_path: './*'
    #       remote_path: '/public_html/site-staging'
    #       sftp_only: true # required by the current server setup
    #       # ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    #       password: ${{ secrets.FTP_SERVER_PASSWORD }}
    #       # delete_remote_files: true # not supported as sftp_only=true prevents directory deletion

    # git-restore-mtime - v2
    # https://github.com/marketplace/actions/git-restore-mtime

    # Restore file modified timestamps to their commit time.
    # This allows the sftp-upload-action to only upload new files to the server
    # instead of reuploading the whole repository even if the files on the server are the same.
    - name: ⏱ Restore timestamps
      uses: chetan/git-restore-mtime-action@v2

    # sftp-upload-action - v2.0.2
    # https://github.com/marketplace/actions/sftp-uploader

    - name: 📂 SFTP uploader                          # Upload to SFTP 
      uses: wangyucode/sftp-upload-action@v2.0.2
      with:
        host: sftp.csc.uvic.ca
        port: 22                                      # Optional, Default to 22.
        username: ${{ secrets.FTP_SERVER_USERNAME }}
        password: ${{ secrets.FTP_SERVER_PASSWORD }}
        compress: true                                # Compression
        forceUpload: false                            # Optional, Force uploading all files, Default to false(upload only newer files).
        localDir: '.'                                 # Required, Absolute or relative to cwd.
        remoteDir: '/public_html/site-staging'        # Required, Absolute path only.
        removeExtraFilesOnServer: true                # Optional, Remove extra files on server. Default to false.
        exclude: '.git/**,.github/**,README.md'       # Optional. exclude patterns (glob) like .gitignore, use ',' to split, Default to ''.
        dryRun: false                                 # Optional. Default to false.
